# BLUE ROOM — REAL ADDRESSES
#
# Emits one directory stub per product route, so the rooms we sell have addresses a person
# would guess instead of a developer parameter. /tarot/ rather than ?dev=drawing-room.
#
# WHY A GENERATOR AND NOT HAND-WRITTEN FILES. Each stub is index.html plus two lines. Hand
# copy it and you own N shells that drift the moment index.html gains a script tag or a
# cache-bust — and index.html changes most weeks. Generated, they cannot drift: this file
# is the only place a route exists, and `python build_routes.py` after any index.html edit
# is the whole maintenance story. Same discipline as codex.html from build_codex.py.
#
# HOW IT WORKS ON A STATIC HOST, with no server config and no redirects:
#   - GitHub Pages serves <dir>/index.html at /<dir>/, so /tarot/ is a real path.
#   - <base href="../"> makes every relative asset in index.html resolve from the site
#     root exactly as it does at /. Verified: all 16 scripts return 200 from /tarot/.
#     It is relative, so it is correct at localhost AND under the /blue-room-scan-room/
#     project path, with nothing to configure and nothing to keep in sync.
#   - window.BR_ROOM names the room; app.js reads it alongside ?dev= (BR-S304).
#
# ?dev= KEEPS WORKING. This adds addresses, it does not remove any. The dev room reaches
# everything the way it always has, and no existing link breaks.

import io, os, sys

ROUTES = [
    # path        room (the value app.js resolves)   what it is
    ("tarot",    "drawing-room",   "The Drawing Room — tarot"),
    ("reading",  "arcane",         "The Arcana intake — the birth reading starts here"),
]

ROOT = os.path.dirname(os.path.abspath(__file__))


def build():
    src = io.open(os.path.join(ROOT, "index.html"), encoding="utf-8").read()

    if "<head>" not in src or '<script src="data.js' not in src:
        sys.exit("build_routes: index.html no longer has the two anchors this depends on "
                 "(<head> and the data.js script tag). Fix the anchors here rather than "
                 "hand-editing a stub -- a hand-edited stub is the thing this file exists "
                 "to prevent.")

    for path, room, label in ROUTES:
        out = src.replace("<head>", '<head>\n  <base href="../" />', 1)
        out = out.replace(
            '<script src="data.js',
            '<!-- GENERATED by build_routes.py -- do not edit. Edit index.html or ROUTES. -->\n'
            '  <script>window.BR_ROOM = "%s";</script>\n'
            '  <script src="data.js' % room, 1)

        # the asserts that make a bad stub fail here rather than on the live site
        assert '<base href="../" />' in out, path
        assert 'window.BR_ROOM = "%s"' % room in out, path
        assert "?dev=" not in out.split("</head>")[0], path

        d = os.path.join(ROOT, path)
        if not os.path.isdir(d):
            os.makedirs(d)
        io.open(os.path.join(d, "index.html"), "w", encoding="utf-8", newline="").write(out)
        print("  /%s/ -> %-16s %s" % (path, room, label))


if __name__ == "__main__":
    print("build_routes: emitting %d real addresses" % len(ROUTES))
    build()
    print("done. Re-run after any index.html change.")
